In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [48]:
def Hamming_dis(V1,V2):
    hammig_distance = np.sum(np.not_equal(V1,V2).astype(int))
    return hammig_distance

def create_w(N,eps):
    w = (np.zeros((N,N)) - eps)
    np.fill_diagonal(w,1)
    return w

def num(x):
    N = np.count_nonzero(x)
    return N

def act_func(input, threshod=0):
    y = np.copy(input)
    y[y<threshod ] = 0
    return y

def find_max_index(x):
    index = np.nonzero(x)[1].item()
    return index

def maxnet(input):
    x = np.copy(input)
    eps = 0.2
    w = create_w(x.shape[1],eps)
    N = num(x)
    i = 0
    while N:
        x = act_func(np.dot(x,w))
        N = num(x)
        i = i+1
        if N == 1:
            break
    index = find_max_index(x)
    return index

In [47]:
X = np.array([[1,-1, 1],[-1, 1,-1],[-1, 1,-1],[1,-1, 1 ]]).reshape(12,1)
Y = np.array([[1,-1, 1],[-1, 1,-1],[-1, 1,-1],[-1, 1,-1]]).reshape(12,1)
A = np.array([[-1, 1,-1],[1,-1, 1],[1, 1, 1 ],[1,-1, 1 ]]).reshape(12,1)
C = np.array([[-1, 1, 1],[1,-1,-1],[1,-1,-1 ],[-1, 1, 1]]).reshape(12,1)

reference = ["X", "Y", "A", "C"]
w = np.concatenate((X/2,Y/2,A/2,C/2),axis=1)
print(w)



[[ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]]


In [30]:
print("Hamming Distance between X and Y: {}".format(Hamming_dis(X,Y)))
print("Hamming Distance between X and A: {}".format(Hamming_dis(X,A)))
print("Hamming Distance between X and C: {}".format(Hamming_dis(X,C)))
print("Hamming Distance between Y and A: {}".format(Hamming_dis(Y,A)))
print("Hamming Distance between Y and C: {}".format(Hamming_dis(Y,C)))
print("Hamming Distance between A and C: {}".format(Hamming_dis(A,C)))




Hamming Distance between X and Y: 3
Hamming Distance between X and A: 8
Hamming Distance between X and C: 8
Hamming Distance between Y and A: 11
Hamming Distance between Y and C: 7
Hamming Distance between A and C: 6


In [59]:
input = np.array([[1, 1, 1],[-1, 1,-1],[-1, 1,-1],[-1, 1,-1]]).reshape(1,12)
b = input.shape[1] / 2
similarity = np.dot(input,w) + b
print("output of HammingNet: ",similarity)
index = maxnet(similarity)
print("\noutput of MaxNet: {} ----> {}".format(index,reference[index]))

output of HammingNet:  [[ 8. 11.  2.  6.]]

output of MaxNet: 1 ----> Y
